feat: 增加resume_list頁面的留言功能
astrocamp/14th-JoBand pull request #106
Opened 2023-09-01 05:57 UTC by fr715464

先依照目前進度增加resume_list頁面的留言功能
後續待貼文及活動頁面出來後再增加
另外點選留言者的名稱可以連到對象的Profile

留言創建
<img width="430" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/130462029/869f26d4-9986-453d-8b11-bfd66c808518">
<img width="335" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/130462029/35fd12ed-5350-44e0-94cb-1cc9ea3a54d9">

留言刪除
<img width="954" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/130462029/27e7e413-1194-4740-84dc-a2370aa65058">

2023-09-01 10:58 UTC, LeoChang0808 commented on app/controllers/comments_controller.rb
> +      render :show
這邊ren show 會有效果嗎🤔️？

2023-09-01 10:58 UTC, LeoChang0808 commented on app/views/comments/_comment.html.erb
> +</ul>
應該是/li

2023-09-02 14:27 UTC, andy840818 requested changes

2023-09-02 14:27 UTC, andy840818 commented on app/views/comments/_comment.html.erb
> +        <%= link_to '刪除', comment_path(comment, resume_list_id: resume_list.id), data: {
data 縮排爆炸

2023-09-02 14:27 UTC, andy840818 commented on db/migrate/20230831060511_create_comments.rb
> +      t.datetime :deleted_at
要做軟刪除 ?

2023-09-02 14:27 UTC, andy840818 commented on app/controllers/comments_controller.rb
> +      render :show
這裡抓的到要 render 誰的 show 🤔️？

2023-09-02 16:32 UTC, fr715464 commented on app/controllers/comments_controller.rb
> +      render :show
修改完會重新推

2023-09-03 07:08 UTC, vito588p requested changes

2023-09-03 07:08 UTC, vito588p commented on app/controllers/comments_controller.rb
> +    @comment.update(deleted_at: Time.now)
已經裝了軟刪除，可以直接寫.destroy 就可以用了
不需要update

[官方文件](https://github.com/rubysherpas/paranoia)有寫

2023-09-03 07:15 UTC, vito588p approved these changes

2023-09-03 14:51 UTC, LeoChang0808 commented on app/views/comments/_comment.html.erb
> +         <%= link_to '刪除', comment_path(comment, resume_list_id: resume_list.id),
包在if 內所以往右兩空格

2023-09-03 14:51 UTC, LeoChang0808 commented on app/views/resume_lists/show.html.erb
> +
上面從form_with開始縮排不太對～

2023-09-03 15:29 UTC, LeoChang0808 approved these changes

2023-09-04 03:43 UTC, codzilla91 approved these changes

2023-09-04 04:17 UTC, merged