Feat : activity CRUD + 活動的 banner 成功上傳至 Amazon S3
astrocamp/14th-JoBand pull request #108
Opened 2023-09-01 13:41 UTC by pjwang0109

- 先做基本的活動系統 CRUD，不然後面的功能都會卡住
- 如果沒問題的話，麻煩大家趕快讓它過～～
- 我接下來會做 搜尋活動 

https://github.com/astrocamp/14th-JoBand/assets/38303979/3aa72328-4999-4c28-ad64-faf674d77d1c

- 發現活動要加時間，多給了開始跟結束的時間
- show 頁面會顯示 ‘時間範圍’
- 活動首頁則只顯示 ‘日期’
<img width="1253" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/38303979/0d5e6a1c-8e4e-4c1c-b8e7-dc98b5c824e4">
<img width="1232" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/38303979/32139d06-ce34-4998-9b3d-edbbcaf6ce68">

- 活動首頁的照片，因為是採用大頭照的方式，把照片秀出來，所以另外加了 _activityBanner.html.erb
- 原先是採用 _banner.html.erb 的預設檔案，但因為尺寸會有問題，所以把 _activityBanner.html.erb 和_banner.html.erb 的預設檔案改成同一張
<img width="1242" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/38303979/5bb8c02c-bcdf-462d-b862-a3a8941e5583">

2023-09-01 14:11 UTC, LeoChang0808 commented on app/controllers/activities_controller.rb
> +      redirect_to activities_path, notice: '成功建立活動'
這邊看要不要改為轉到那個活動的show
目前profile 跟band都是成功轉到show

2023-09-01 14:11 UTC, LeoChang0808 commented on app/controllers/activities_controller.rb
> +      redirect_to activities_path, notice: '更新成功'
同上～

2023-09-01 14:11 UTC, LeoChang0808 commented on app/views/activities/index.html.erb
> +            <%= link_to '刪除', activity_path(activity), data: { turbo_method: 'delete', turbo_confirm: '確定要刪除嗎？' } %>
更新刪除應該在show裡面比較適合

2023-09-01 14:11 UTC, LeoChang0808 commented on test/controllers/activities_controller_test.rb
test 資料夾刪除

2023-09-02 02:29 UTC, LeoChang0808 commented on app/views/bands/show.html.erb
> +      <%= link_to '創建活動', new_activity_path, class:'joband-action-btn mx-5' %>
這邊往前縮兩個空格，跟上方end對齊

2023-09-02 02:29 UTC, LeoChang0808 commented on app/views/activities/show.html.erb
> +<%# <% if current_user&.id == @activity.user_id %>
這邊可以先刪掉，給關聯性那張票來做就好

2023-09-02 02:29 UTC, LeoChang0808 commented on app/views/activities/show.html.erb
> +    <%# <%= link_to '刪除', activity_path(activity), data: { turbo_method: 'delete', turbo_confirm: '確定要刪除嗎？' } %>
這個上面有重複可以刪

2023-09-02 02:29 UTC, LeoChang0808 commented on test/fixtures/activities.yml
這個跟底下的test可以刪～整個test 資料夾都刪就好

2023-09-02 04:20 UTC, LeoChang0808 commented on app/views/activities/index.html.erb
> +
這邊雖然不用修改刪除，還是要把每個活動撈出來🙆🏻‍♂️方法可以參考profile 跟 band 可以免去each的方法，在activities 資料夾下面有個_activity的erb檔案，就可以在這邊用render @activities的方法不用each

2023-09-02 07:06 UTC, LeoChang0808 approved these changes

2023-09-02 07:10 UTC, vito588p commented on test/fixtures/activities.yml
沒寫test 可以不用

2023-09-02 07:56 UTC, vito588p approved these changes

2023-09-02 08:16 UTC, fr715464 approved these changes

2023-09-02 13:52 UTC, andy840818 requested changes

2023-09-02 13:52 UTC, andy840818 commented on db/migrate/20230901024732_create_activities.rb
> +      t.date :founded_at
感覺 founded at 的語意不太對,我覺得 begin at 或 starts at 會好一點

2023-09-02 13:52 UTC, andy840818 commented on app/views/activities/_activity.html.erb
> +    <p class="w-full font-semibold joband-text-bk h2 joband-shadow"><%= activity.title %></p>
包這麼長, 感覺換行會比較好讀, 像你 banner 那樣
```
<p class="w-full font-semibold joband-text-bk h2 joband-shadow">
  <%= activity.title %>
</p>
```

2023-09-02 13:52 UTC, andy840818 commented on app/views/activities/_form.html.erb
> +        <%= f.label '活動標題' %>
縮排縮成 4 格了

2023-09-02 13:52 UTC, andy840818 commented on app/views/activities/edit.html.erb
> +    <h2 class="my-5 text-4xl font-bold text-white">編輯您的活動</h2>
縮排縮成4格

2023-09-02 13:52 UTC, andy840818 commented on config/routes.rb
> +  resources :activities, shallow: true
沒有嵌套不需要寫 shallow

2023-09-02 13:52 UTC, andy840818 commented on app/controllers/activities_controller.rb
> +      render :new, notice: '建立失敗'
失敗要寫 alert: 才會有 X 的符號 , 不然他會變成打勾

2023-09-02 13:52 UTC, andy840818 commented on app/controllers/activities_controller.rb
> +      render :edit, notice: '更新失敗'
同上

2023-09-02 13:52 UTC, andy840818 commented on app/views/activities/show.html.erb
> +    <div class="mb-6"><%= link_to '刪除活動', activity_path(@activity), data: { turbo_method: 'delete', turbo_confirm: '確定要刪除嗎？' }, class: "joband-tag-seniority" %></div>
可以參考 resume_list 的縮排

2023-09-03 01:28 UTC, vito588p commented on app/views/activities/_form.html.erb
> +        <%= f.text_field :location %>
這裡縮排還是沒改到，4, 5 , 9, 10, 14, 15, 19, 20, 24, 25, 29, 30, 34, 35, 40 行

2023-09-03 04:50 UTC, vito588p approved these changes

2023-09-03 06:49 UTC, andy840818 approved these changes

2023-09-03 06:50 UTC, merged