feat:增加討論區留言功能
astrocamp/14th-JoBand pull request #145
Opened 2023-09-11 06:21 UTC by fr715464

增加討論區留言功能

點擊留言圖示後會長出表格
<img width="796" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/130462029/2a732240-c6e0-4cc2-b79a-ad89f9f9994a">
輸入留言
<img width="803" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/130462029/fbbbfbfa-ee09-43c9-9627-44f598560167">
<img width="759" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/130462029/bd25dce3-a62b-4bcc-b0bc-ffcd527ba4df">

2023-09-11 10:45 UTC, LeoChang0808 approved these changes

2023-09-11 12:23 UTC, vito588p approved these changes

2023-09-12 08:27 UTC, codzilla91 approved these changes

2023-09-12 08:30 UTC, vito588p requested changes
index 已經做了 partial render ，我再修改

2023-09-12 08:30 UTC, vito588p commented on app/views/posts/index.html.erb
> +          <div class="px-4 border-2 border-b border-x-0">
這邊已經做partial render了

2023-09-13 00:45 UTC, vito588p approved these changes

2023-09-13 00:45 UTC, merged