style: Band's CSS ( show, new, edit, index )
astrocamp/14th-JoBand pull request #25
Opened 2023-08-17 08:42 UTC by andy840818

先把有關 Band 的CSS 大致刻好 , 
比較特別的部分是 裝了 [**Action Text**](https://guides.rubyonrails.org/action_text_overview.html#what-is-action-text-questionmark) , 
遇到的**問題點** : 
再執行安裝指令後 `rails action_text:install` 這個套件會自動也安裝 `Active Storage` 所以在我pull完 profile的分支後, 遇到有相同的migration名 , 而無法開啟rails 
**解決**: 保留線上有的migration , 把我本地多餘的砍掉。

https://github.com/astrocamp/14th-JoBand/assets/132435587/a3d5a563-75f1-4f01-a05a-3df43c90589c
new
![127 0 0 1_3000_bands_new_locale=tw](https://github.com/astrocamp/14th-JoBand/assets/132435587/d041d32d-c5b8-4327-b85e-d1560101ad9b)
show
![127 0 0 1_3000_bands_2_locale=tw](https://github.com/astrocamp/14th-JoBand/assets/132435587/44fa8176-7887-4158-aee4-d8ad6e34f931)
index
![127 0 0 1_3000_bands](https://github.com/astrocamp/14th-JoBand/assets/132435587/f08bd176-05f4-4d5a-b39d-d494619a79ca)

2023-08-19 00:49 UTC, LeoChang0808 commented on app/views/bands/show.html.erb
> -<p>Status: <%= @band.state %></p>
這邊好像沒縮到排@@ 整個應該是包在上面的 article id="band_show" 下
然後給他ID是因為之後 CSS 會用到嗎?

2023-08-19 00:49 UTC, LeoChang0808 commented on app/controllers/application_controller.rb
> +  around_action :switch_locale
這邊不太了解為什麼要在每個action 前跟後 都做switch_locale的動作@@

2023-08-19 05:02 UTC, andy840818 commented on app/assets/stylesheets/vanilla.css
> @@我們有用到vanilla css嗎🤔️

check box的 label 需要手刻

2023-08-19 05:31 UTC, LeoChang0808 requested changes

2023-08-19 05:31 UTC, LeoChang0808 commented on app/assets/stylesheets/vanilla.css
那應該可以寫在 tailwind 那邊就好 ~ 我看那邊你也有定義個 check-box~
而且 vanilla.css 要用好像還需要 import or 寫進<head>
但如果只是要放手刻沒有要用到 vanilla 的功能就放 tailwind CSS 裡面就好不用再裝一個 CSS 套件?

2023-08-19 05:32 UTC, andy840818 commented on app/controllers/application_controller.rb
> +  around_action :switch_locale
這是i18n 要替換上面網址用的 [詳情請見](https://guides.rubyonrails.org/i18n.html)

2023-08-19 05:32 UTC, andy840818 commented on app/assets/stylesheets/vanilla.css
這不是套件啦 XD 這是我新增的檔案而已

2023-08-19 05:37 UTC, LeoChang0808 commented on app/assets/stylesheets/vanilla.css
XD 那你寫在 tailwind 就好~或是真想用 vanilla.css 檔名的話好像 tailwind.css 底下要 import 你這個檔名~
像是你 import actiontext.css 那樣? 不然應該會吃不到 vanilla.css 裡面的設定 ? 因為 layout 的 head 目前CSS只吃 tailwind 那個檔案 XD
![image](https://github.com/astrocamp/14th-JoBand/assets/135109935/eecccc31-e604-44e5-afed-dfb2092abe10)

2023-08-19 05:43 UTC, andy840818 commented on app/assets/stylesheets/vanilla.css
這不用特別寫 , 可以吃的到喔 因為上層有這個
![CSS require](https://github.com/astrocamp/14th-JoBand/assets/132435587/8fe21a09-edc6-489b-94f5-83ef24652ee3)

2023-08-19 05:59 UTC, LeoChang0808 commented on app/assets/stylesheets/vanilla.css
原來如此 !! 有吃到就好
建議可能 vanilla 檔名看要不要改一下 XD
因為一開始會錯意以為是 vanilla CSS 套件~
如果專門處理 check-box 或 band 的 CSS 要不要改成 check_box.css 或是 Band.css 會比較容易懂

2023-08-19 08:46 UTC, andy840818 commented on app/assets/stylesheets/vanilla.css
當初是想說 vanilla 是代稱原生的意思, 
好 那我改成 Band.css

2023-08-19 11:00 UTC, andy840818 commented on app/views/bands/show.html.erb
> -<p>Status: <%= @band.state %></p>
你是說哪裡沒有縮到 ?
對 我給id 是要改字體顏色

2023-08-19 11:46 UTC, LeoChang0808 commented on app/views/bands/show.html.erb
> -<p>Status: <%= @band.state %></p>
沒事～眼花看錯🤣
看到紅色那排🫠該休息一下了😵

2023-08-19 12:45 UTC, LeoChang0808 approved these changes

2023-08-19 17:20 UTC, vito588p approved these changes

2023-08-19 17:32 UTC, fr715464 approved these changes

2023-08-20 07:13 UTC, codzilla91 approved these changes

2023-08-20 10:07 UTC, pjwang0109 approved these changes

2023-08-20 11:14 UTC, merged