feat:創建Recruit及Recrui與Instrument的第三方表格,並Rubocop處理完畢
astrocamp/14th-JoBand pull request #27
Opened 2023-08-17 12:26 UTC by fr715464

已完成Recruit的Model及CRUD並可正常使用

並創建第三方表格Model:recruit_and_instrument來接受Recrui與Instrument的相關資料

後續關聯性的方面會在陸續補上

<img width="368" alt="截圖 2023-08-17 下午8 23 15" src="https://github.com/astrocamp/14th-JoBand/assets/130462029/baf25c65-c14b-4c79-8872-2dac08d46d25">

<img width="361" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/130462029/e80504cd-aea7-4f3d-91b7-f4d5edb9bc21">

<img width="260" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/130462029/63e2ca5d-e24a-4b6d-bf4e-8f80ecf1c2c0">

2023-08-18 02:38 UTC, LeoChang0808 commented on app/controllers/recruits_controller.rb
> +    params.require(:recruit).permit(:recruit_title, :instrument, :condition, :practice_time, :area,
樂器用了多對多:instrument沒這欄位可以去掉了🙆🏻‍♂️

2023-08-18 02:43 UTC, andy840818 commented on app/controllers/recruits_controller.rb
> +    @recruit = Recruit.find(params[:id])
有before_action 這行可以刪掉

2023-08-18 02:47 UTC, andy840818 commented on app/models/band.rb
> +  end
24 - 43行，要刪掉，這是在 style 還在 Band 裡面時用的東西

2023-08-18 02:49 UTC, LeoChang0808 commented on app/controllers/recruits_controller.rb
> +    @instruments = Instrument.all
@instruments = Instrument.all 這個可以不用

2023-08-18 02:51 UTC, andy840818 commented on app/views/recruits/_form.html.erb
> +	<% end %>
縮排要調整一下

2023-08-18 03:28 UTC, andy840818 requested changes

2023-08-18 03:28 UTC, andy840818 commented on app/views/recruits/show.html.erb
這頁的縮排也爆炸

2023-08-18 13:05 UTC, fr715464 commented on app/views/recruits/index.html.erb
> +<% @recruits.each do  |recruit| %>
有跑過一次,修正後會再跑一次

2023-08-18 21:40 UTC, zhanjian0217 commented on app/models/recruit.rb
> +  has_many :instruments, through: :recruit_and_instrument
```ruby
  has_many :instruments, through: :recruit_and_instrument, dependent: :destroy
```

2023-08-18 21:40 UTC, zhanjian0217 commented on app/controllers/recruits_controller.rb
> +    @instruments = Instrument.all
這邊可以放在 `before_action`，因為 `:new, :edit` 都會用到

或是可以直接選擇將 `Instrument.all` 放在 view 的表單上，這樣 `11, 24` 行就可以刪掉了

若是不想再 view 上面直接去 query 資料庫的話，就教給 viewhelper

可以參考 `bands_helper.rb` 的寫法

2023-08-18 21:40 UTC, zhanjian0217 commented on app/controllers/recruits_controller.rb
> +    @recruit.instrument_ids = []
在 `recruit.rb` 加上 `dependent: :destroy`
這句話就可以刪了

2023-08-18 21:40 UTC, zhanjian0217 commented on app/views/recruits/_form.html.erb
> +    <% end %>
```erb
<%= f.collection_check_boxes :instrument_ids, @instruments, :id, :name %>
```

2023-08-18 21:40 UTC, zhanjian0217 commented on app/views/recruits/_form.html.erb
> +          Recruit.areas.map{|k, v| [k.to_s , k.to_s]} %>
```erb
<%= f.select :area, Recruit.areas.keys %>
```

2023-08-18 21:40 UTC, zhanjian0217 commented on app/views/recruits/edit.html.erb
> +<%= render'form',recruit:@recruit %>
```erb
# 要求一下空格
<%= render 'form', recruit: @recruit %> 
```

2023-08-18 21:40 UTC, zhanjian0217 commented on app/views/recruits/new.html.erb
> +<%= render'form',recruit:@recruit %>
同上

2023-08-18 21:40 UTC, zhanjian0217 commented on db/migrate/20230817104211_add_band_id_for_recruit.rb
> +    add_column :recruits, :band_id, :bigint
https://apidock.com/rails/v6.1.3.1/ActiveRecord/ConnectionAdapters/SchemaStatements/add_reference


```ruby
  add_reference :recruits, :band, foreign_key: true
```

2023-08-20 12:46 UTC, vito588p commented on app/views/recruits/index.html.erb
> +         <% @recruits.each do  |recruit| %>
這排縮排還是沒改到喔

2023-08-20 12:46 UTC, vito588p commented on app/views/recruits/_form.html.erb
> +		<p>使用樂器 instrument </p>
縮排

2023-08-20 12:46 UTC, vito588p commented on app/views/recruits/_form.html.erb
> +	  <%= f.collection_check_boxes :instrument_ids, @instruments, :id, :name do |i| %>
縮排

2023-08-20 14:52 UTC, fr715464 commented on app/views/recruits/_form.html.erb
> +	  <%= f.collection_check_boxes :instrument_ids, @instruments, :id, :name do |i| %>
<img width="717" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/130462029/9ced4cc8-45c5-4ece-a15b-1e5a25a8c045">
其實我都排好了 但傳上來就是會亂掉

2023-08-21 03:46 UTC, closed without merging