feat: 增加樂團創建功能
astrocamp/14th-JoBand pull request #6
Opened 2023-08-08 11:36 UTC by andy840818

<h1>建立樂團功能</h1> 
未做CSS 

- 比較難的部分是 new 
曲風的表單是使用 check_box , 因為需要可以複選 , 意思就是要讓database能存一組序列
所以在model 加了 ` serialize :styles, Array `  把資料序列化 
strong params 就要給他一個 [ ] `styles:[]` 才能寫入複數的資料
但`serialize`會把資料 序列化为 YAML 格式的字符串 
寫入會長得像這樣 `--- - '' - Rock - Hip-hop - Metal` 前面多一個空格 
我就用 `reject` 方法 在存入之前 把空格去掉, 就可以拿到正常的序列 
```ruby
before_save :set_styles

    def set_styles
      self.styles = self.styles.reject{|e| e.empty? }
    end
```

創立樂團頁面
bands/new 
![bands-new](https://github.com/astrocamp/14th-JoBand/assets/132435587/db30429d-8920-483f-a919-558b731bb5bb)

我設計成功建立樂團之後頁面會轉到，剛才建立完的show

樂團show
bands/:id
![bands-show](https://github.com/astrocamp/14th-JoBand/assets/132435587/726ecbba-0415-4d82-bb9d-cd30a3be7b0d)

樂團列表
bands
![bands-index](https://github.com/astrocamp/14th-JoBand/assets/132435587/9393e954-f05c-46ea-b3be-62ae051da2df)

2023-08-08 13:27 UTC, fr715464 approved these changes

2023-08-08 13:29 UTC, fr715464 approved these changes

2023-08-08 15:35 UTC, fr715464 commented on app/controllers/bands_controller.rb
> +        redirect_to band_path(band_id), notice: '更新成功'
這邊應該redirect_to band_path, notice: '更新成功' 
就可以了,(band_id)這個應該不需要

2023-08-09 02:25 UTC, LeoChang0808 requested changes
不太了解表單序列化那邊，但看起來應該是存得進去
在想之後做樂團的index卡片那邊不知道撈不撈的到
![image](https://github.com/astrocamp/14th-JoBand/assets/135109935/b4f4ecf5-792d-4aa8-9412-93d835ede5b6)
能否能否試試看在 rails c 裡面 
b1 = Band.first
印出 b1.style.first 這樣能不能撈到~之後方便做樂團卡片用

另外就是有些縮排調一下 XD 這樣之後整合上去就不用在調一次~ ^^b

2023-08-09 02:25 UTC, LeoChang0808 commented on app/views/bands/index.html.erb
> +<% end %>
縮排~~XD

2023-08-09 02:25 UTC, LeoChang0808 commented on app/views/bands/show.html.erb
> +    <%#= button_to '招募中', new_registration_path(band_id: @band.id), method: :get %>
這邊是先預留招募的空位所以先註解掉嗎:D?

2023-08-09 02:49 UTC, pjwang0109 approved these changes

2023-08-09 09:52 UTC, andy840818 commented on app/views/bands/show.html.erb
> +    <%#= button_to '招募中', new_registration_path(band_id: @band.id), method: :get %>
預想是做招募中 可以點進去 然後創立申請表

2023-08-09 09:59 UTC, codzilla91 approved these changes

2023-08-11 09:25 UTC, vito588p commented
hi~來確認一下，這條目前還需要修改是嗎？

2023-08-11 14:53 UTC, andy840818 commented
> hi~來確認一下，這條目前還需要修改是嗎？

可以先pull 因為東西可以動 之後改動應該不會有衝突 不然再做下去怕下次PR東西太多

2023-08-11 16:42 UTC, vito588p approved these changes

2023-08-12 06:28 UTC, closed without merging